# Generated by Django 3.2 on 2023-01-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.taxi'),
        ),
    ]
